import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Queryclintprovider from "./components/Queryclintprovider";
import Scorecontextprovider from "./components/contexts/Scorecontext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/bgimg.png')] bg-center min-h-screen bg-cover  
   `}
   cz-shortcut-listen="true"

      >
        <Queryclintprovider>
          <Scorecontextprovider>
            <div className="w-full min-h-screen ">
            {children}

        </div>

          </Scorecontextprovider>
           

        </Queryclintprovider>
       
         
      </body>
    </html>
  );
}
